### ISSUE TITLE
[BUG] Error while dumping SQLite database: no such file or directory

### ISSUE THREAD

**Issue by Kazdan1994** [8byr0/strapi-plugin-backup-restore#1]
Hi. I just try to use your plugin and encourter the following errors.

Backup Failure

Something went wrong while creating backup

Starting sqlite3 backup from undefined
Dumping to /home/$USER/strapi-project/private/backups/1626884931704/database.db
Directory created successfully!
Error: ENOENT: no such file or directory, copyfile '/home/$USER/strapi-project/undefined' -> '/home/$USER/strapi-project/private/backups/1626884931704/database.db'

Thank you for explain :)

Strapi Version            │ 3.6.5 (node v14.17.0)

**Comment by 8byr0** [comment]
@Kazdan1994 Thanks for your feedback. 
I just released a new version(0.5.0) adding support for postgres that fixes this issue.

**Comment by 8byr0** [comment]
@Kazdan1994 can you confirm all's now fine on your side ?

**Comment by Kazdan1994** [comment]
Hi @8byr0,

I confirm the issue is fix for 0.5.0. Thank you for your plugin and have a good continuation.
